version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ../
      dockerfile: devops-pipeline-fase-2/containers/backend/Dockerfile
    container_name: crm-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_PATH=/app/data/database.sqlite
    volumes:
      - ./data:/app/data
      - backend_node_modules:/app/node_modules
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on: []

  # Frontend Service  
  frontend:
    build:
      context: ../
      dockerfile: devops-pipeline-fase-2/containers/frontend/Dockerfile
    container_name: crm-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      - backend

# Volumes
volumes:
  backend_node_modules:
    driver: local

# Networks
networks:
  crm-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16