networks:
  crm-network:
    driver: bridge

volumes:
  crm-data:
    driver: local

services:
  backend:
    build:
      context: ~/devops/CRM-System
      dockerfile: devops-pipeline-fase-2/containers/backend/Dockerfile
    container_name: crm-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_PATH=/app/data/database.sqlite
    volumes:
      - crm-data:/app/data
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  frontend:
    build:
      context: ~/devops/CRM-System
      dockerfile: devops-pipeline-fase-2/containers/frontend/Dockerfile
    container_name: crm-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped